### ISSUE TITLE
代码无法运行，python3.9是必须的吗？

### ISSUE THREAD

**Issue by CY-Christin** [yjqiang/novel-downloader#1]
现在的版本是3.8.10
提示报错
```
[novel-downloader] python3 main_crawler.py               
Traceback (most recent call last):
  File "main_crawler.py", line 4, in <module>
    import dict_str_class
  File "/cyyyyyy/python/novel-downloader/dict_str_class.py", line 1, in <module>
    from loader.playwright_loaders import PlaywrightBodyPageLoader, PlaywrightIndexPageLoader
  File "/cyyyyyy/python/novel-downloader/loader/playwright_loaders.py", line 6, in <module>
    from loader.base_loaders import BodyPageLoader, IndexPageLoader
  File "/cyyyyyy/python/novel-downloader/loader/base_loaders.py", line 6, in <module>
    from my_dataclass.content import ContentParagraph, ContentWords, ContentImage
  File "/cyyyyyy/python/novel-downloader/my_dataclass/content.py", line 30, in <module>
    class ContentImage:
  File "/cyyyyyy/python/novel-downloader/my_dataclass/content.py", line 41, in ContentImage
    def to_json(self) -> dict[str, str]:
TypeError: 'type' object is not subscriptable

```

**Comment by yjqiang** [comment]
是的，必须 3.9
